#!/bin/bash

RPI="rpi01 rpi02 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpi18 rpi19 rpi20"

if [ $# -eq 0 ] ; then
	DIR=$RPI
else
	DIR=$*
fi

for file in $DIR ; do


	for pi in $RPI ; do

		if ping -c 1 -W 1 $pi > /dev/null 2>&1 ; then
			echo "$pi : alive"
		else
			echo "$pi : dead"
		fi
	done

done

exit 0
